networks:
  cluster_net:

name: tfl_buses

services:
  neo4j1:
    image: neo4j-custom:4.4
    hostname: neo4j1
    build: &build
      dockerfile: ./neo4j.Dockerfile
    networks: &networks
      - cluster_net
    ports:
      - 17474:7474
      - 17687:7687
    volumes: &volumes
      - ./data:/var/lib/neo4j/import
      - ./backups:/backups
    profiles: [db]
    environment: &env
      NEO4J_AUTH: neo4j/changeme
      NEO4J_ACCEPT_LICENSE_AGREEMENT: yes
      NEO4J_dbms_memory_heap_max__size: 2g
      NEO4J_dbms_memory_pagecache_size: 256m
      NEO4J_dbms_mode: CORE
      NEO4J_causal__clustering_initial__discovery__members: neo4j1:5000,neo4j2:5000,neo4j3:5000
      NEO4J_dbms_connector_bolt_advertised__address: localhost:17687
      NEO4J_dbms_routing_enabled: true
      NEO4J_dbms_routing_default__router: SERVER
      NEO4J_dbms_security_procedures_unrestricted: apoc.*,custom.*
      NEO4J_apoc_export_file_enabled: true
      NEO4J_dbms_logs_query_format: JSON
      NEO4J_internal_dbms_logs_query_deprecation__notifications_enabled: true
      NEO4J_metrics_bolt_messages_enabled: false
      NEO4J_metrics_cypher_replanning_enabled: true
      NEO4J_dbms_logs_query_rotation_size: 5MiB
      NEO4J_dbms_logs_query_rotation_keep__number: 5
  
  neo4j2:
    image: neo4j-custom:4.4
    hostname: neo4j2
    # build: *build
    networks: *networks
    ports:
      - 27474:7474
      - 27687:7687
    volumes: *volumes
    profiles: [db]
    environment:
      <<: *env
      NEO4J_dbms_connector_bolt_advertised__address: localhost:27687
  
  neo4j3:
    image: neo4j-custom:4.4
    hostname: neo4j3
    # build: *build
    networks: *networks
    ports:
      - 37474:7474
      - 37687:7687
    volumes: *volumes
    profiles: [db]
    environment:
      <<: *env
      NEO4J_dbms_connector_bolt_advertised__address: localhost:37687

  neo4j4:
    image: neo4j-custom:4.4
    hostname: neo4j4
    # build: *build
    networks: *networks
    ports:
      - 47474:7474
      - 47687:7687
      - 46362:6362
    volumes: *volumes
    profiles: [db]
    environment:
      <<: *env
      NEO4J_dbms_mode: READ_REPLICA
      NEO4J_dbms_connector_bolt_advertised__address: localhost:47687
      NEO4J_dbms_backup_listen__address: neo4j4:6362


  app:
    hostname: app
    image: bus-app:1.0
    build: ./app
    networks: *networks
    ports:
      - 8080:8080
    profiles: [app]
    environment:
      - SPRING_NEO4J_URI=neo4j://neo4j1:7687